### ISSUE TITLE
Adjustable HttpClient Timeout

### ISSUE THREAD

**Issue by JanRomero** [experimentaltvcenter/InternetArchive.NET#3]
Hi,

thanks for this lib, I don’t know why archive.org’s HTTP API has to be so annoying.

I realize the timeout issue is mentioned in the docs, but I’m not sure how to implement it correctly. Is there a way to change the timeout without doing DI? I just have a console app where I call `Client.Create()`.

Would you be open to exposing the HttpClient directly?

Currently I’m doing disgusting reflection voodoo to change the timeout, which works, but you know…

```csharp
var field = archive.GetType().GetProperty("HttpClient", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
var client = field?.GetValue(archive) as HttpClient;
if (client is not null)
    client.Timeout = TimeSpan.FromMinutes(30);
```

It’s also pretty annoying to upload for 15 minutes only to get a timeout. Maybe a better default might be something small, so large audio/video uploads fail early and smaller files remain unaffected?

Coincidentally, 15 to 20 minutes is about the time my uploads take (~250 MB).

Thanks!

**Comment by experimentaltv** [comment]
I landed on the 15 minute default because some Internet Archive API calls were terminating connections after 15 minutes from their side. It was also the only setting that resulted in unit tests behaving consistently. I realize this is imperfect.

The most reliable method for you may be to adjust the multipart upload parameters in ```Item.PutRequest```:

```
MultipartUploadMinimumSize = 1024 * 1024 * 32, // 32 MB
MultipartUploadChunkSize = 1024 * 1024 * 8 // upload in 8 MB chunks
```

The DI stuff is meant to be used like this:

```
ServiceExtensions.Services.AddInternetArchiveDefaultRetryPolicies();
ServiceExtensions.Services.AddInternetArchiveServices(TimeSpan.FromMinutes(30));
```

I'll add a ```SetTimeout``` method to the client to make this easier and more discoverable. Please let me know if this works for you.

**Comment by JanRomero** [comment]
Ah, sweet, thank you for the quick reply! I didn’t realize you could chunk uploads like that. Should have looked at the commented source code instead of VS’s decompilation of the NuGet package 😀

**Comment by experimentaltv** [comment]
Version 4.2.0 adds a ```SetTimeout``` method to the client. I also improved the documentation around timeouts and chunked uploads. Thank you for the feedback.
